### ISSUE TITLE
small mapping issues for the xbox one controller in 0.12.1

### ISSUE THREAD

**Issue by Lite5h4dow** [libcala/stick#36] opened 2021-08-03 08:03 UTC
**Current Mapping**
Left Bumper mapped as `ActionH`
Right Bumper mapped as `ActionD`
MenuL mapped as `BumperL`
MenuR mapped as `BumperR`
Left Trigger mapped as `JoyZ`
Right Trigger mapped as `CamZ`
X Button mapped as `ActionC`
Y Button mapped as `ActionV`
Xbox Button (big one in the middle) unmapped `Unmapped Linux Button 139`

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by AldaronLau** [comment] 2021-08-03 18:14
@Lite5h4dow what's the Joystick ID printed out by the example program?

**Comment by Lite5h4dow** [comment] 2021-08-03 18:29
Connected p1, id: 05005E04E0020309, name: Xbox Wireless Controller

**Comment by Lite5h4dow** [comment] 2021-08-03 18:33
L thumbstick press mapped as `TriggerL`
R thumbstick press mapped as `TriggerR`

**Comment by AldaronLau** [comment] 2021-08-03 19:37
@Lite5h4dow can you check out the current main branch, and make sure it works correctly with the added mapping?

**Comment by Lite5h4dow** [comment] 2021-08-03 19:47
forgive me but ive forgotten how to use a git repo in the compile again

**Comment by AldaronLau** [comment] 2021-08-03 19:55
@Lite5h4dow yeah, that should work.

**Comment by Lite5h4dow** [comment] 2021-08-03 20:22
almost perfect, x is now  `ActionH` and y is `ActionY`

**Comment by AldaronLau** [comment] 2021-08-03 20:31
Due to the fact that X and Y are in different locations on different gamepads, `ActionH` (horizontal) and `ActionV` (vertical) are used instead of having `ActionX` and `ActionY` in stick.  This decision was made so that programmers who want and to code an upwards action, such as jumping or opening a game inventory don't have to check whether to bind it to X or Y, and can reserve the horizontal action for an alternate (besides `ActionA`) action such as using an item.  The names "X" and "Y" have no specific meaning unlike "A" and "B", so they're named by physical location.  So it sounds like it works as intended, I'll release version 0.12.2 shortly.

**Comment by AldaronLau** [comment] 2021-08-03 20:54
@Lite5h4dow just released the new version on crates.io, so closing.

**Closed by AldaronLau** 2021-08-03 20:54 UTC

**Comment by Lite5h4dow** [comment] 2021-08-03 21:16
thanks again man!
