### ISSUE TITLE
examples/haptic.rs dosent run correctly

### ISSUE THREAD

**Issue by Lite5h4dow** [libcala/stick#27] opened 2021-05-25 18:23 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
copy 'examples/haptic.rs' into main.rs
compile,
run

**Expected behaviour**
should feel a rumble after running the program, however, I get no response.

**Desktop (please complete the following information):**
 - OS: Raspian (Linux)

**Comment by AldaronLau** [comment] 2021-05-26 02:14
@Lite5h4dow that's not what haptic.rs is supposed to do (maybe the name is too misleading?).

haptic.rs should start an event loop, while you:
 - press A: Full power rumble
 - press B: Low power rumble
 - press Home: Exit event loop

When you release the button the rumble should stop.

**Comment by Lite5h4dow** [comment] 2021-05-26 02:23
> @Lite5h4dow that's not what haptic.rs is supposed to do (maybe the name is too misleading?).
> 
> haptic.rs should start an event loop, while you:
>  - press A: Full power rumble
>  - press B: Low power rumble
>  - press Home: Exit event loop
> 
> When you release the button the rumble should stop.

Yeah, none of that happens though. I don't even get a message saying a controller has connected and when I added a printline toggle beginning of the function that didn't print either.

**Comment by AldaronLau** [comment] 2021-05-26 02:28
@Lite5h4dow interesting.  I'm guessing the function with the `println!()` at the beginning of it is the `event_loop()` function?  That seems like a bug, I'll look into it.

**Comment by Lite5h4dow** [comment] 2021-05-26 02:31
For your convenience here is my implementation of it (fyi I tried it both not in the main thread and in the main thread and neither worked) https://www.github.com/Lite5h4dow/camera-rig/tree/master/src%2Fmain.rs

**Comment by AldaronLau** [comment] 2021-05-26 02:32
@Lite5h4dow Thanks!

**Comment by AldaronLau** [comment] 2021-05-26 02:47
@Lite5h4dow I think I will have to test this on my Raspberry Pi when I get a chance.  I cannot reproduce the error.  I can't run the following code due to a panic:

```rust
    let step = Pin::new(23);
    step.with_exported(||{
        step.set_direction(Direction::Out).unwrap();
        loop{
            micros_pulse(step, 1);
            sleep(Duration::from_micros(650));
        }
    }).unwrap()
```

Commenting it out does make the program terminate immediately, but that's to be expected; Adding

```
thread.join();
```

To the end of main lets the main thread wait for the controller thread, and "Hello from the controller thread" prints out.  If you do that, do you get the same behavior?

**Comment by Lite5h4dow** [comment] 2021-05-26 19:32
> @Lite5h4dow I think I will have to test this on my Raspberry Pi when I get a chance. I cannot reproduce the error. I can't run the following code due to a panic:
> 
> ```rust
>     let step = Pin::new(23);
>     step.with_exported(||{
>         step.set_direction(Direction::Out).unwrap();
>         loop{
>             micros_pulse(step, 1);
>             sleep(Duration::from_micros(650));
>         }
>     }).unwrap()
> ```
> 
> Commenting it out does make the program terminate immediately, but that's to be expected; Adding
> 
> ```
> thread.join();
> ```
> 
> To the end of main lets the main thread waits for the controller thread, and "Hello from the controller thread" prints out. If you do that, do you get the same behaviour?

unfortunately, it didn't work. I'm getting no message even if I remove it from a separate thread and remove my code.

**Comment by Lite5h4dow** [comment] 2021-05-26 20:23
so I copy-pasted it into another crate and compiled it for rpi0 and I got the connection event but it appears to be frozen. no response from any of the buttons, I can't end the session and the buttons have no haptic feedback.

**Comment by AldaronLau** [comment] 2021-05-26 20:40
@Lite5h4dow it could be that there isn't an existing mapping for that controller.  What's the id it prints out?

**Comment by Lite5h4dow** [comment] 2021-05-26 20:59
id: 0300_5E04_EA02_0103. its an xbox one controller

**Comment by Lite5h4dow** [comment] 2021-05-26 21:00
(i would have assumed the disconnect event would have fired even if the mapping didn't exist right?)

**Comment by AldaronLau** [comment] 2021-05-26 21:06
@Lite5h4dow yeah, it should...

**Comment by Lite5h4dow** [comment] 2021-05-26 23:03
yeah no disconnected event triggered or connection event triggered after the initial connected event. looks like it hung somewhere without erroring.

**Comment by Lite5h4dow** [comment] 2021-06-01 10:04
any luck?

**Comment by AldaronLau** [comment] 2021-06-01 14:33
@Lite5h4dow haven't gotten to it yet, hopefully I'll get to it later this week.

**Comment by Lite5h4dow** [comment] 2021-06-01 20:33
after some more testing, i can confirm that it responds to no event after connection. nothing happens.

**Comment by Lite5h4dow** [comment] 2021-06-01 20:34
unfortunately im not good enough at rust to work on other peoples code, sorry i cant help fixing this.

**Comment by AldaronLau** [comment] 2021-06-02 03:27
@Lite5h4dow no worries, I think I should be able to set up my pi and a controller in a way to debug this.

**Comment by Lite5h4dow** [comment] 2021-06-04 17:13
@AldaronLau any luck bud?

**Comment by Lite5h4dow** [comment] 2021-06-16 12:05
@AldaronLau any chance to look at this?

**Comment by AldaronLau** [comment] 2021-06-16 20:35
> so I copy-pasted it into another crate and compiled it for rpi0 and I got the connection event but it appears to be frozen. no response from any of the buttons, I can't end the session and the buttons have no haptic feedback.

@Lite5h4dow I've been able to reproduce this behavior (on a Linux laptop), but it doesn't happen every time.  I think I might have some ideas on why this is happening.

**Comment by AldaronLau** [comment] 2021-06-21 03:08
@Lite5h4dow Can you try the main branch and see if the problem still happens?

**Comment by Lite5h4dow** [comment] 2021-06-21 15:39
@AldaronLau cant wait to give this a go but I cant seem to reference the code from github:
![image](https://user-images.githubusercontent.com/18059545/122789350-23671500-d2af-11eb-83f4-3792b199cd3f.png)
I get the following error:
![image](https://user-images.githubusercontent.com/18059545/122789447-3da0f300-d2af-11eb-8767-9574757bddd5.png)

**Comment by Lite5h4dow** [comment] 2021-06-21 15:42
also fails with the stick dependancy as follows:
![image](https://user-images.githubusercontent.com/18059545/122789897-b1db9680-d2af-11eb-88e6-0584737c11d1.png)

same error

**Comment by AldaronLau** [comment] 2021-06-21 17:55
@Lite5h4dow I think you want to do:

```toml
[dependencies]
sysfs_gpio = "0.5"
stick = { git = "https://github.com/libcala/stick", branch = "main" }
pasts = "0.6"
```

Also, I should note that the API changed slightly, so minor changes might be needed (you'll at least need to replace `stick::Controller::listener()` with `stick::Listener::default()`).  Feel free to clone this repository and run `cargo doc --open` to see the new documentation / examples with pasts version 0.8.

**Comment by Lite5h4dow** [comment] 2021-06-21 18:17
no luck with that unfortunately,
![image](https://user-images.githubusercontent.com/18059545/122808852-4c92a000-d2c5-11eb-94c1-07c6fec8c88c.png)
![image](https://user-images.githubusercontent.com/18059545/122808886-54eadb00-d2c5-11eb-9fab-663c830de8b7.png)

**Comment by AldaronLau** [comment] 2021-06-21 18:31
@Lite5h4dow it works for me - you might be running an old version of cargo.  Can you try

```bash
git clone https://github.com/libcala/stick.git
cd stick/
cargo run --example haptic`
```

If the example program works, then yours should be able to when the new version comes out.

**Comment by Lite5h4dow** [comment] 2021-06-21 19:51
@AldaronLau 
The problem is if I cont compile it on raspberry pi, then I cant confirm for sure. either way, it doesn't work.
![image](https://user-images.githubusercontent.com/18059545/122819422-5b338400-d2d2-11eb-8889-139ec9f3bcaa.png)

**Comment by Lite5h4dow** [comment] 2021-06-21 20:11
also got this when compiling on windows from master / main.
```
error[E0423]: expected function, tuple struct or tuple variant, found struct `crate::Controller`
   --> stick\src\ffi\windows.rs:684:49
    |
684 |                           Event::Connect(Box::new(crate::Controller(Ctlr::new(
    |  _________________________________________________^
685 | |                             id,
686 | |                         )))),
    | |__________________________^ help: use struct literal syntax instead: `crate::Controller { remap: val, raw: val, btns: val, nums: val, axis: val }`
    |
   ::: stick\src\ctlr.rs:239:1
    |
239 | / pub struct Controller {
240 | |     // Shared remapping.
241 | |     remap: Rc<Info>,
242 | |     //
...   |
249 | |     axis: [f64; Axs::Count as usize],
250 | | }
    | |_- `crate::Controller` defined here

error[E0308]: mismatched types
   --> stick\src\ctlr.rs:265:18
    |
265 |             .get(&raw.id())
    |                  ^^^^^^^^^ expected `u64`, found array `[u8; 8]`
    |
    = note: expected reference `&u64`
               found reference `&[u8; 8]`

error[E0308]: mismatched types
   --> stick\src\ctlr.rs:284:9
    |
283 |     pub fn id(&self) -> u64 {
    |                         --- expected `u64` because of return type
284 |         self.raw.id()
    |         ^^^^^^^^^^^^^ expected `u64`, found array `[u8; 8]`

error[E0599]: no method named `axis` found for struct `Ctlr` in the current scope
   --> stick\src\ctlr.rs:336:26
    |
336 |                 self.raw.axis(v).clamp(-1.0, 1.0)
    |                          ^^^^ method not found in `Ctlr`
    |
   ::: stick\src\ffi\windows.rs:702:1
    |
702 | pub(crate) struct Ctlr {
    | ---------------------- method `axis` not found for this

error[E0599]: no method named `axis` found for struct `Ctlr` in the current scope
   --> stick\src\ctlr.rs:344:22
    |
344 |             self.raw.axis(v).clamp(-1.0, 1.0)
    |                      ^^^^ method not found in `Ctlr`
    |
   ::: stick\src\ffi\windows.rs:702:1
    |
702 | pub(crate) struct Ctlr {
    | ---------------------- method `axis` not found for this

error[E0599]: no method named `pressure` found for struct `Ctlr` in the current scope
   --> stick\src\ctlr.rs:362:26
    |
362 |                 self.raw.pressure(v).clamp(0.0, 1.0)
    |                          ^^^^^^^^ method not found in `Ctlr`
    |
   ::: stick\src\ffi\windows.rs:702:1
    |
702 | pub(crate) struct Ctlr {
    | ---------------------- method `pressure` not found for this

error[E0599]: no method named `pressure` found for struct `Ctlr` in the current scope
   --> stick\src\ctlr.rs:370:22
    |
370 |             self.raw.pressure(v).clamp(0.0, 1.0)
    |                      ^^^^^^^^ method not found in `Ctlr`
    |
   ::: stick\src\ffi\windows.rs:702:1
    |
702 | pub(crate) struct Ctlr {
    | ---------------------- method `pressure` not found for this

error[E0599]: no variant or associated item named `Connect` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:684:32
    |
684 |                         Event::Connect(Box::new(crate::Controller(Ctlr::new(
    |                                ^^^^^^^
    |                                |
    |                                variant or associated item not found in `Event`
    |                                help: there is a variant with a similar name: `Context`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `Connect` not found here

error[E0599]: no variant or associated item named `Next` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:811:65
    |
811 | ...                   self.pending_events.push(Event::Next(
    |                                                       ^^^^ variant or associated item not found in `Event`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `Next` not found here

error[E0599]: no variant or associated item named `Prev` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:817:65
    |
817 | ...                   self.pending_events.push(Event::Prev(
    |                                                       ^^^^ variant or associated item not found in `Event`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `Prev` not found here

error[E0599]: no variant or associated item named `JoyPush` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:859:65
    |
859 | ...                   self.pending_events.push(Event::JoyPush(
    |                                                       ^^^^^^^ variant or associated item not found in `Event`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `JoyPush` not found here

error[E0599]: no variant or associated item named `CamPush` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:865:65
    |
865 | ...                   self.pending_events.push(Event::CamPush(
    |                                                       ^^^^^^^ variant or associated item not found in `Event`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `CamPush` not found here

error[E0599]: no variant or associated item named `DpadUp` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:871:65
    |
871 | ...                   self.pending_events.push(Event::DpadUp(
    |                                                       ^^^^^^ variant or associated item not found in `Event`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `DpadUp` not found here

error[E0599]: no variant or associated item named `DpadDown` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:877:65
    |
877 | ...                   self.pending_events.push(Event::DpadDown(
    |                                                       ^^^^^^^^ variant or associated item not found in `Event`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `DpadDown` not found here

error[E0599]: no variant or associated item named `DpadLeft` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:883:65
    |
883 | ...                   self.pending_events.push(Event::DpadLeft(
    |                                                       ^^^^^^^^ variant or associated item not found in `Event`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `DpadLeft` not found here

error[E0599]: no variant or associated item named `DpadRight` found for enum `Event` in the current scope
   --> stick\src\ffi\windows.rs:889:65
    |
889 | ...                   self.pending_events.push(Event::DpadRight(
    |                                                       ^^^^^^^^^
    |                                                       |
    |                                                       variant or associated item not found in `Event`
    |                                                       help: there is a variant with a similar name: `HatRight`
    |
   ::: stick\src\event.rs:15:1
    |
15  | pub enum Event {
    | -------------- variant or associated item `DpadRight` not found here

error[E0061]: this function takes 0 arguments but 1 argument was supplied
   --> stick\src\listener.rs:37:14
    |
37  |         Self(crate::ffi::Hub::new(remap))
    |              ^^^^^^^^^^^^^^^^^^^^ ----- supplied 1 argument
    |              |
    |              expected 0 arguments
    |
note: associated function defined here
   --> stick\src\ffi\windows.rs:646:19
    |
646 |     pub(super) fn new() -> Self {
    |                   ^^^

error[E0308]: mismatched types
  --> stick\src\listener.rs:45:9
   |
44 |     fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
   |                                                            ------------------ expected `Poll<Controller>` because of return type
45 |         Pin::new(&mut self.get_mut().0).poll(cx)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Controller`, found tuple
   |
   = note: expected enum `Poll<Controller>`
              found enum `Poll<(usize, Event)>`

error: aborting due to 18 previous errors

Some errors have detailed explanations: E0061, E0308, E0423, E0599.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `stick`

To learn more, run the command again with --verbose.
```

**Comment by AldaronLau** [comment] 2021-06-21 22:02
@Lite5h4dow Can you not do a `git clone` on your raspberry pi?

As for the Windows port, I was changing a couple things on the Linux port and haven't yet gotten around to changing them for the Windows port as well.

**Comment by Lite5h4dow** [comment] 2021-06-21 22:06
@AldaronLau its a raspberry pi zero, dosent have the ram to compile anything

**Comment by AldaronLau** [comment] 2021-06-21 22:18
@Lite5h4dow I imagine you must have a way to cross-compile it though (with linker from https://github.com/raspberrypi/tools) and then use scp to deploy it?

**Comment by Lite5h4dow** [comment] 2021-06-21 22:21
@AldaronLau That's what I'm doing, just using a docker container so I can do it from windows too. that's where the errors are from.

**Comment by AldaronLau** [comment] 2021-06-21 22:28
@Lite5h4dow Oh, I thought you were running a Linux PC for that.  The panic is the same one from #28, so I'm not sure how to verify if this one's fixed without fixing that issue first.

**Comment by AldaronLau** [comment] 2021-07-01 22:41
@Lite5h4dow any chance to test this again?

**Comment by Lite5h4dow** [comment] 2021-07-02 11:20
attempted to get this running from the git project, got this error this time.
```
error: failed to get `stick` as a dependency of package `Stick-test v0.1.0 (/home/lotus/Projects/Stick-test)`

Caused by:
  failed to load source for dependency `stick`

Caused by:
  Unable to update https://github.com/libcala/stick?branch=main

Caused by:
  failed to update submodule `gcdb`

Caused by:
  failed to fetch submodule `gcdb` from git@github.com:gabomdq/SDL_GameControllerDB.git

Caused by:
  failed to authenticate when downloading repository

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  error authenticating: no auth sock variable; class=Ssh (23)
```

**Comment by Lite5h4dow** [comment] 2021-07-02 12:09
@AldaronLau cant compile it because ssh is used to compile gcdb. would it be possible to use https instead?
```
Attaching to pi-compile_1
pi-compile_1  |     Updating git repository `https://github.com/AldaronLau/pasts`
pi-compile_1  |     Updating git repository `https://github.com/libcala/stick`
pi-compile_1  |     Updating git submodule `git@github.com:gabomdq/SDL_GameControllerDB.git`
pi-compile_1  | error: failed to get `stick` as a dependency of package `Stick-test v0.1.0 (/usr/src)`
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to load source for dependency `stick`
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   Unable to update https://github.com/libcala/stick?branch=main#5102fc29
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to update submodule `gcdb`
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to fetch submodule `gcdb` from git@github.com:gabomdq/SDL_GameControllerDB.git
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to authenticate when downloading repository
pi-compile_1  | 
pi-compile_1  |   * attempted ssh-agent authentication, but no usernames succeeded: `git`
pi-compile_1  | 
pi-compile_1  |   if the git CLI succeeds then `net.git-fetch-with-cli` may help here
pi-compile_1  |   https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   error authenticating: no auth sock variable; class=Ssh (23)
pi-compile_1 exited with code 101
```

**Comment by AldaronLau** [comment] 2021-07-02 18:52
@Lite5h4dow just changed it to https, hopefully that fixes it?

**Comment by Lite5h4dow** [comment] 2021-07-02 19:03
```Attaching to pi-compile_1
pi-compile_1  |     Updating git submodule `git@github.com:gabomdq/SDL_GameControllerDB.git`
pi-compile_1  | error: failed to get `stick` as a dependency of package `Stick-test v0.1.0 (/usr/src)`
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to load source for dependency `stick`
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   Unable to update https://github.com/libcala/stick?branch=main#5102fc29
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to update submodule `gcdb`
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to fetch submodule `gcdb` from git@github.com:gabomdq/SDL_GameControllerDB.git
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   failed to authenticate when downloading repository
pi-compile_1  | 
pi-compile_1  |   * attempted ssh-agent authentication, but no usernames succeeded: `git`
pi-compile_1  | 
pi-compile_1  |   if the git CLI succeeds then `net.git-fetch-with-cli` may help here
pi-compile_1  |   https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
pi-compile_1  | 
pi-compile_1  | Caused by:
pi-compile_1  |   error authenticating: no auth sock variable; class=Ssh (23)
pi-compile_1 exited with code 101
```
same thing I think

**Comment by AldaronLau** [comment] 2021-07-02 19:16
@Lite5h4dow so when I do a fresh clone with:

```bash
git clone git@github.com:libcala/stick.git --recursive
```

I get this:

```output
Cloning into 'stick'...
remote: Enumerating objects: 2982, done.
remote: Counting objects: 100% (493/493), done.
remote: Compressing objects: 100% (344/344), done.
remote: Total 2982 (delta 275), reused 325 (delta 124), pack-reused 2489
Receiving objects: 100% (2982/2982), 1017.82 KiB | 4.89 MiB/s, done.
Resolving deltas: 100% (2255/2255), done.
Submodule 'gcdb' (https://github.com/gabomdq/SDL_GameControllerDB.git) registered for path 'gcdb'
Cloning into '/home/aldaronlau/libcala/stick/gcdb'...
remote: Enumerating objects: 1941, done.        
remote: Counting objects: 100% (501/501), done.        
remote: Compressing objects: 100% (61/61), done.        
remote: Total 1941 (delta 458), reused 450 (delta 440), pack-reused 1440        
Receiving objects: 100% (1941/1941), 643.15 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (1191/1191), done.
Submodule path 'gcdb': checked out 'c3738c2112072f4ab03f35ef7a1c1367d123d534'
```

Can you try that (it should do the same thing)?

**Comment by Lite5h4dow** [comment] 2021-07-02 19:29
The problem is the use of SSH, I can clone and compile it on my machine, but I'm crosscompiling in a docker container with no SSH key or an account associated with a key, meaning it can't clone with SSH.

**Comment by AldaronLau** [comment] 2021-07-02 19:31
@Lite5h4dow it should do the same thing with:

```bash
git clone https://github.com/libcala/stick.git --recursive
```

without using SSH at all.

**Comment by Lite5h4dow** [comment] 2021-07-02 19:42
this is my cargo.toml
```toml
[package]
name = "Stick-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stick = {git="https://github.com/libcala/stick", branch="main"}
pasts = {git="https://github.com/AldaronLau/pasts", branch="main"}
```
how would you run the example after cloning?

**Comment by AldaronLau** [comment] 2021-07-02 19:46
@Lite5h4dow change it to:

```toml
[package]
name = "Stick-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stick = {path="/path/to/cloned/stick"}
pasts = {git="https://github.com/AldaronLau/pasts", branch="main"}
```

Also you can use pasts from crates.io: `pasts = "0.8.0"`

**Comment by Lite5h4dow** [comment] 2021-07-02 20:01
i get this now
```
Attaching to pi-compile
pi-compile  |     Updating git repository `https://github.com/AldaronLau/pasts`
pi-compile  | error: failed to get `stick` as a dependency of package `Stick-test v0.1.0 (/usr/src)`
pi-compile  | 
pi-compile  | Caused by:
pi-compile  |   failed to load source for dependency `stick`
pi-compile  | 
pi-compile  | Caused by:
pi-compile  |   Unable to update /usr/stick
pi-compile  | 
pi-compile  | Caused by:
pi-compile  |   found a virtual manifest at `/usr/stick/Cargo.toml` instead of a package manifest
pi-compile exited with code 101
```

**Comment by AldaronLau** [comment] 2021-07-02 20:05
@Lite5h4dow that's because the stick/ repository is a workspace, so if your Cargo.toml looks like this:

```toml
[package]
name = "Stick-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stick = {path="/usr/stick"}
pasts = {git="https://github.com/AldaronLau/pasts", branch="main"}
```

change it to:

```toml
[package]
name = "Stick-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stick = {path="/usr/stick/stick"}
pasts = {git="https://github.com/AldaronLau/pasts", branch="main"}
```

**Comment by Lite5h4dow** [comment] 2021-07-02 20:30
Good and bad news
Good news, im getting a print out of events and it is no longer freezing
Bad news, I'm not getting any haptic feedback

**Comment by AldaronLau** [comment] 2021-07-02 20:57
@Lite5h4dow I have a feeling that the Pi Zero can't handle the amount of power needed for haptic feedback.  I might try testing this on a Pi 4 to see if there's a difference.

**Comment by Lite5h4dow** [comment] 2021-07-02 21:01
i would agree, however it pulls power for haptics from the batteries. ill give it a go on my pi3b+ tho.

**Comment by Lite5h4dow** [comment] 2021-07-02 21:03
@AldaronLau, yeah no dice on the 3B+ either.

**Comment by AldaronLau** [comment] 2021-07-03 20:48
@Lite5h4dow https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=132882&p=889965#p889965 looks like haptic is disabled in the raspberry pi kernel, unless you build it custom yourself.  Using the `fftest` program installed with the `joystick` package on raspbian the force feedback test prints `Error: Function not implemented`, which means the error is not an error with the stick crate - so I'm closing this issue.

**Closed by AldaronLau** 2021-07-03 20:48 UTC
Labels: bug

**Comment by Lite5h4dow** [comment] 2021-07-03 21:26
Awesome thanks for everything man, really appreciate the effort you are putting into this! One day when I'm better with rust I might be able to come back and actually help.

**Comment by Lite5h4dow** [comment] 2021-07-03 21:35
@AldaronLau does this mean the crate will get updated too?

**Comment by AldaronLau** [comment] 2021-07-04 04:15
@Lite5h4dow Thanks, it's nice to see my work appreciated!  I will try to update the crate soon on crates.io - the bluetooth issue you found is something I hope isn't too hard to fix before the next release - now that I know why it's happenning.

**Comment by AldaronLau** [comment] 2021-07-07 23:43
@Lite5h4dow I just updated the crate on crates.io to version 0.12.0
